import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button';
import BcitBuilding from '@/components/BcitBuilding';
import Logo from '@/components/Logo';
import Copyright from '@/components/Copyright';
import Text from '@/components/Text';
import SocialMedia from '@/components/SocialMedia';

var name = process.env.NEXT_PUBLIC_NAME;
export default function Home() {
  return (
    <>
      <Head>
        <title>Jill Class 14</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {name}

        <div className={styles.middle}>
          <div>
            <BcitBuilding />
          </div>

          <div className={styles.textandbutt}>
            <div>
              <Text />
            </div>

            <div>
              <Button />
            </div>
          </div>

          <div>
            <Logo />
          </div>
        </div>
      </main>

      <div className={styles.footer}>
        <div>
          <Copyright />
        </div>

        <div>
          <SocialMedia />
        </div>
      </div>
    </>
  )
}
